
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: try_out_blog_2_development

test:
  <<: *default
  database: try_out_blog_2_test

production:
  url: <%= ENV['DATABASE_URL'] %>
